services:
  c7platform:
    image: camunda/camunda-bpm-platform:latest
    container_name: camunda7platform
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform

  c7experiment:
    image: moritz148/camunda-7-experiment:latest
    container_name: c7experiment

    networks:
      - camunda-platform
    depends_on:
        c7platform:
          condition: service_healthy