services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    container_name: camunda7
    restart: unless-stopped
    ports:
      - "8080:8080"
#    healthcheck:
#      test: ["CMD", "curl", "-fs", "http://camunda7:8080/engine-rest/engine"]
#      interval: 20s
#      timeout: 5s
#      retries: 5
    networks:
      - camunda-platform




  c7experiment:
    image: moritz148/cam7exp:latest
    container_name: c7experiment
    restart: unless-stopped
    depends_on:
      - camunda
    networks:
      - camunda-platform

networks:
  camunda-platform:
    driver: bridge