services:
  c7platform:
    image: camunda/camunda-bpm-platform:latest
    container_name: camunda7platform
    restart: unless-stopped
    #ports:
    #  - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8080/engine-rest/engine" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - camunda-platform

  c7experiment:
    image: moritz148/cam7exp:latest
    container_name: c7experiment
    networks:
      - camunda-platform
    depends_on:
        c7platform:
          condition: service_healthy

networks:
  camunda-platform:
    driver: bridge